### PR TITLE
modify Required: changing into suitable input and output format

### PR DESCRIPTION
**Pull request by vikram-gk**
I don't want waste yours and Nikhil time, So modify it into suitable format
If you guys can tolerate till tomorrow, I can get my charger and  finish it in  half an hour. I don't have anaconda in air nor python

### CODE REVIEW

**Comment by craterkamath** [comment]
Handled in commit 618668036297e5ae0e3a3fcb820d9ce4a41fc172

**Comment by vikramgopal** [comment]
F...ker could have added it and modified......

**Comment by craterkamath** [comment]
You cant use spline interpolation for dates. You should have read before bitch!

**Comment by craterkamath** [comment]
> F...ker could have added it and modified......
> Don't be selfish...

modifying your code means removing everything and writing again, Which is what I did

**Comment by craterkamath** [comment]
> F...ker could have added it and modified......
> Don't be selfish...

Did u atleast open the commit and read what I did?

**Comment by craterkamath** [comment]
> F...ker could have added it and modified......
> Don't be selfish...

.pynb file for a module is useless. Anyway I'll have to remove that and put it into a .py file later because you cant import from a .pynb file.

**Comment by craterkamath** [comment]
> I don't want waste yours and Nikhil time, So modify it into suitable format
> If you guys can tolerate till tomorrow, I can get my charger and finish it in half an hour. I don't have anaconda in air nor python

BASE LINE: You cant modify into suitable format because it doesnt support time data for interpolation. And stop comlpaining. 
@vikramgopal 
okay-you-stop-complaining-no-one-really-cares

**Comment by craterkamath** [comment]
> U can convert dates into suitable index and then use spline xD

But then it's completely irrational to convert random numbers to dates back @vikramgopal . Do your homework kid!

**Comment by craterkamath** [comment]
Plus spline's the worst to impute for time series because it'll remove the residuals and only leave smoothened trend which is not what we want.

**Pull request closed without merging**
